#!/bin/sh

if peg src/crustmark/parse.rustpeg > src/crustmark/parse.gen.rs; then
    cat <<HEADER > src/crustmark/parse.rs
// Generated by generate.sh.
// You may want to edit parse.rustpeg or parse.preamble.rs.
HEADER
    cat src/crustmark/parse.preamble.rs           >> src/crustmark/parse.rs
    cat src/crustmark/parse.gen.rs | sed '/^#!/d' >> src/crustmark/parse.rs
fi

rm -f src/crustmark/parse.gen.rs
