#!/bin/sh

if peg src/markdown_parser.rustpeg > src/markdown_parser.gen.rs; then
    cat <<HEADER > src/markdown_parser.rs
// Generated by generate.sh.
// You may want to edit markdown_parser.rustpeg or markdown_parser.preamble.rs.
HEADER
    cat src/markdown_parser.preamble.rs >> src/markdown_parser.rs
    cat src/markdown_parser.gen.rs      >> src/markdown_parser.rs
fi

rm -f src/markdown_parser.gen.rs
